### ISSUE TITLE
Node.js 16.4.0 and 16.4.1 support

### ISSUE THREAD

**Issue by Hongbo-Miao** [renovatebot/docker-node#123]
Similar to https://github.com/renovatebot/renovate/issues/10212

Would be great to add the new Node.js 16.4.0 and 16.4.1 too, thanks!

**Comment by rarkins** [comment]
@viceice I updated the trigger file but it sure that’s enough?

**Comment by viceice** [comment]
i think the issue is, that renovate only allow node lts as stable, so we don't get any other node versions here. i think we need to change the versioning. Working on it.

**Comment by viceice** [comment]
fixed

**Comment by Hongbo-Miao** [comment]
Hmm, seems still not working. Tested half hour ago. For example, [this pull request](https://github.com/Hongbo-Miao/hongbomiao.com/pull/2815), the app expects Renovate uses `16.4.1`, but because it is missing, it is using 14.17.1 currently.

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: undefined
npm ERR! notsup Not compatible with your version of node/npm: undefined
npm ERR! notsup Required: {"node":"16.4.1","npm":"7.x"}
npm ERR! notsup Actual:   {"npm":"7.19.1","node":"v14.17.1"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/renovate-cache/others/npm/_logs/2021-07-07T10_48_00_733Z-debug.log
```

![image](https://user-images.githubusercontent.com/3375461/124751072-cdee6180-df58-11eb-9fc4-88ccfa82ed97.png)

**Comment by viceice** [comment]
v16.4.1 is not yet released

**Comment by viceice** [comment]
fixed in https://github.com/renovatebot/docker-node/pull/128

need to wait for https://github.com/renovatebot/docker-node/runs/3008414264?check_suite_focus=true to finish

**Comment by viceice** [comment]
released 🎉

**Comment by Hongbo-Miao** [comment]
Thanks for the help, @viceice !
